version: '3.9'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - /app/node_modules
    
    environment:
      - NODE_ENV=development
      - PORT=8000
      - CHOKIDAR_USEPOLLING=true 
      - CHOKIDAR_POLLING_INTERVAL=1000

    command: npm run dev


    