version: '3.9'


services:
  prod:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production

    ports:
      - "8000:8000"

    environment:
      - NODE_ENV=production
      - PORT=8000

    command: npm start
    restart: unless-stopped